services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  In2code\Groupmailer\:
    resource: '../Classes/*'

  In2code\Groupmailer\Service\MailService:
    public: true

  In2code\Groupmailer\Command\GenerateMailQueueCommand:
    public: true
    tags:
      - name: 'console.command'
        command: 'groupmailer:generateMailQueue'
        schedulable: true

  In2code\Groupmailer\Command\ProcessMailQueueCommand:
    public: true
    tags:
      - name: 'console.command'
        command: 'groupmailer:processMailQueue'
        schedulable: true
